# Customer ID=4313; Build=0xa64b0; Copyright (c) 2023 by Cadence Design Systems.  ALL RIGHTS RESERVED.
# These coded instructions, statements, and computer programs are the
# copyrighted works and confidential proprietary information of Tensilica Inc.
# They may not be modified, copied, reproduced, distributed, or disclosed to
# third parties in any manner, medium, or form, in whole or in part, without
# the prior written consent of Tensilica Inc.

CACHE_ATTR=0x44441144
NUM_CORES=2
DSP_0_DEVICE_COMM_BASE_MAGIC=0x90000000
DSP_1_DEVICE_COMM_BASE_MAGIC=0x90001000

